[package]
name = "howie"
description = "https://beacons.ai/howiethecrab"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.0"
nix = "0.26.2"
