name: SOL Market CI

on:
  push:
    branches: ["main"]
    paths:
      - market_sol/**
      - .github/**
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - name: Download the repo
        uses: actions/checkout@v3
      - name: Test
        uses: ./.github/workflows/run_tests
        with:
          unitn_username: ${{secrets.UNITN_USERNAME}}
          unitn_password: ${{secrets.PANCAKES}}
          kellnr_token: ${{secrets.KELLNR_TOKEN}}
        # See comment in that file on why that code is not here
